posts/urls.py
from django.urls import path
from posts.views import PostsView, PostDetailView, AddReviewView, EditReviewView, PostsHomeView,\
    ConfirmDeleteReview, DeleteReviewView, PostCreate

app_name = "posts"
urlpatterns = [
    path("", PostsView.as_view(), name="list"),
    path('home/', PostsHomeView.as_view(), name='home'),
    path("<int:id>/", PostDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name = "reviews"),
    path("<int:post_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name = "edit-review"),
    path("<int:post_id>/reviews/<int:review_id>/delete/confirm/",
         ConfirmDeleteReview.as_view(), name="confirm-delete-review"
         ),
    path("<int:post_id>/reviews/<int:review_id>/delete/",
         DeleteReviewView.as_view(), name="delete-review"
         ),
    path('create/', PostCreate.as_view(), name="create"),
]

postssite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import main_page

urlpatterns = [
    path("", main_page, name="main_page"),
    path('users/', include("users.urls")),
    path("posts/", include("posts.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = "users"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    profile_picture = models.ImageField(default="default_profile_pic.png")

users/forms.py
from django import forms
from users.models import CustomUser


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def save(self, commit=True):
        user = super().save(commit)
        user.set_password(self.cleaned_data['password'])
        user.save()

        return user

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email', 'profile_picture')

users/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from users.forms import UserCreateForm, UserUpdateForm


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            'form': create_form
        }
        return render(request, "users/register.html", context)

    def post(self, request):
        create_form = UserCreateForm(data=request.POST)

        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, "users/register.html", context)


class LoginView(View):
    def get(self, request):
        login_form = AuthenticationForm()

        return render(request, "users/login.html", {'login_form': login_form})

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, "You have successfully logged in.")
            return redirect("posts:list")
        else:
            return render(request, "users/login.html", {'login_form': login_form})

class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        if not request.user.is_authenticated:
            return redirect("users:login")
        return render(request, "users/profile.html", {"user": request.user})


class LogoutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("main_page")

class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        return render(request, "users/profile_edit.html", {"form": user_update_form})

    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request, "You have successfully updated your profile")

            return redirect("users:profile")
        return render(request, "users/profile_edit.html", {"form": user_update_form})

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Login Page{% endblock %}

{% block content %}

    <h3>Login</h3>
    <div class="row">
        <div class="col-4">
            <form method="post">
                {% csrf_token %}

                {{login_form | crispy }}
                <a href="{% url 'posts:home' %}"><button class="btn btn-primary" type="submit">Log in</button></a> <span class="ms-3">No account? Then, <a href="{% url 'users:register' %}">get registered</a></span>
            </form>
        </div>
    </div>


{% endblock %}

users/templates/users/profile.html
{% extends "base.html" %}

{% block title %}Profile Page{% endblock %}

{% block content %}

    <h3>Profile</h3>

<img class="profile-pic" src="{{ user.profile_picture.url }}" alt="profile picture">

    <div>
        <a href="{% url 'users:profile-edit' %}">edit Profile</a>
    </div>

    <p>Username: {{ user.username }}</p>
    <p>First Name: {{ user.first_name }}</p>
    <p>Last Name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>

{% endblock %}

users/templates/users/profile_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <h3>Edit Profile</h3>

  <div class="row">
    <div class="col-4">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form | crispy }}
        <button class="btn btn-primary">save chenges</button>
      </form>
    </div>

  </div>


{% endblock %}

users/templates/users/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}Register Page {% endblock %}

{% block content %}
    <h3>Register</h3>
    <div class="row">
        <div class="col-4">
            <form action="{% url 'users:register' %}" method="post">

                {% csrf_token %}
                {{ form | crispy }}

                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
{%endblock %}