posts/urls.py
from django.urls import path
from posts.views import PostsView, PostDetailView, AddReviewView, EditReviewView, PostsHomeView,\
    ConfirmDeleteReview, DeleteReviewView, PostCreate

app_name = "posts"
urlpatterns = [
    path("", PostsView.as_view(), name="list"),
    path('home/', PostsHomeView.as_view(), name='home'),
    path("<int:id>/", PostDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name = "reviews"),
    path("<int:post_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name = "edit-review"),
    path("<int:post_id>/reviews/<int:review_id>/delete/confirm/",
         ConfirmDeleteReview.as_view(), name="confirm-delete-review"
         ),
    path("<int:post_id>/reviews/<int:review_id>/delete/",
         DeleteReviewView.as_view(), name="delete-review"
         ),
    path('create/', PostCreate.as_view(), name="create"),
]

postssite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import main_page

urlpatterns = [
    path("", main_page, name="main_page"),
    path('users/', include("users.urls")),
    path("posts/", include("posts.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, ProfileView, LogoutView, ProfileUpdateView

app_name = "users"
urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name='login'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/edit/", ProfileUpdateView.as_view(), name="profile-edit"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Postssite{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body class="mx-5">

<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main_page' %}">Postsite</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'posts:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'posts:list' %}">Posts</a>
            </li>
        </ul>

        <div class="me-5">
            {% if request.user.is_authenticated %}
                <ul class="navbar-nav ">
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          {{ request.user.username }}
                      </a>
                      <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="{% url 'posts:create' %}">Create post</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'users:logout' %}">Log out</a></li>
                      </ul>
                    </li>
                </ul>

            {% else %}
                <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Login</a>
            {% endif %}

        </div>
    </div>
  </div>
</nav>

<div class="container">
    {% if messages %}
        <div class="mt-4">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        </div>

</div>
{% endif %}
{% block content %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/main.html
{% extends "base.html" %}


{% block content %}
    <h1>Main Page</h1>
    <p>O'zaro xabarlar almashish portaliga Xush Kelibsiz!</p>
    <a href="{% url 'main_page' %}"></a>
{% endblock %}