posts/urls.py
from django.urls import path
from posts.views import PostsView, PostDetailView, AddReviewView, EditReviewView, PostsHomeView,\
    ConfirmDeleteReview, DeleteReviewView, PostCreate

app_name = "posts"
urlpatterns = [
    path("", PostsView.as_view(), name="list"),
    path('home/', PostsHomeView.as_view(), name='home'),
    path("<int:id>/", PostDetailView.as_view(), name="detail"),
    path("<int:id>/reviews/", AddReviewView.as_view(), name = "reviews"),
    path("<int:post_id>/reviews/<int:review_id>/edit/", EditReviewView.as_view(), name = "edit-review"),
    path("<int:post_id>/reviews/<int:review_id>/delete/confirm/",
         ConfirmDeleteReview.as_view(), name="confirm-delete-review"
         ),
    path("<int:post_id>/reviews/<int:review_id>/delete/",
         DeleteReviewView.as_view(), name="delete-review"
         ),
    path('create/', PostCreate.as_view(), name="create"),
]

postssite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import main_page

urlpatterns = [
    path("", main_page, name="main_page"),
    path('users/', include("users.urls")),
    path("posts/", include("posts.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.middleware import get_user
from django.utils import timezone

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.timezone import now

from users.models import CustomUser



class Post(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    post_picture = models.ImageField(default='default_post.png')
    created_at = models.DateTimeField(default=timezone.now)
    views_count = models.IntegerField(default=0)
    last_viewed_at = models.DateTimeField(null=True, blank=True)
    is_approved = models.BooleanField(default=False)

    def increment_views(self):
        self.views_count += 1
        self.last_viewed_at = now()
        self.save()

    def __str__(self):
        return self.title



class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def full_name(self):
        return f"{self.first_name} {self.last_name}"

class PostAuthor(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.post.title} by {self.author.first_name} {self.author.last_name}"

class PostReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    created_at = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return f"{self.stars_given} stars by {self.user.username}"

posts/forms.py
from django import forms

from posts.models import PostReview, Post


class PostReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)
    class Meta:
        model = PostReview
        fields = ('stars_given', 'comment')

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'post_picture']

posts/views.py
from datetime import timedelta
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.timezone import now
from django.views import View
from posts.forms import PostReviewForm, PostForm
from posts.models import Post, PostReview, PostAuthor, Author


class PostCreate(LoginRequiredMixin, View):
    def get(self, request):
        form = PostForm()
        return render(request, 'posts/create.html', {'form': form})

    def post(self, request):
        if request.method == "POST":
            form = PostForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.created_at = now()
                post.save()

                author, created = Author.objects.get_or_create(
                    email=request.user.email,
                    defaults={"first_name": request.user.first_name, "last_name": request.user.last_name}
                )

                if not PostAuthor.objects.filter(post=post, author=author).exists():
                    PostAuthor.objects.create(post=post, author=author)

                return redirect('posts:list')
        else:
            form = PostForm()

        return render(request, 'posts/create.html', {'form': form})

    # def post(self, request):
    #     form = PostForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         form.save()
    #
    #         author, created = Author.objects.get_or_create(
    #             email=request.user.email,
    #             defaults={"first_name": request.user.first_name, "last_name": request.user.last_name}
    #         )
    #         PostAuthor.objects.create(post=self.post, author=author)
    #
    #         return redirect('posts:list')
    #     return render(request, 'posts/create.html', {'form': form})



class PostsView(View):

    def get(self, request):
        posts = Post.objects.filter(is_approved=True).order_by('-created_at')
        return render(request, "posts/list.html", {'posts': posts})


class PostsHomeView(View):
    def get(self, request):
        new_posts = Post.objects.filter(is_approved=True).order_by('-created_at') [:5]
        most_viewed_posts = Post.objects.filter(is_approved=True).order_by('-views_count') [:5]
        one_week_ago = timezone.now() - timedelta(days=7)
        recent_viewed_posts = Post.objects.filter(is_approved=True, last_viewed_at__gte=one_week_ago).order_by('-last_viewed_at') [:5]

        context = {
            'new_posts': new_posts,
            'most_viewed_posts': most_viewed_posts,
            'recent_viewed_posts': recent_viewed_posts,
        }
        return render(request, 'posts/home.html', context)


class PostDetailView(View):
    def get(self, request, id):
        post = Post.objects.get(id=id)
        review_form = PostReviewForm()
        return render(request, "posts/detail.html", {"post": post, "review_form": review_form} )

    def get(self, request, id,):
        post = get_object_or_404(Post, id = id)
        post.views_count += 1
        post.last_viewed_at = timezone.now()
        post.save()
        return render(request, 'posts/detail.html', {'post':post})

class AddReviewView( LoginRequiredMixin, View):
    def post(self, request, id):
        post = Post.objects.get(id=id)
        reviews_form = PostReviewForm(data=request.POST)

        if reviews_form.is_valid():
            PostReview.objects.create(
                post = post,
                user = request.user,
                stars_given = reviews_form.cleaned_data['stars_given'],
                comment = reviews_form.cleaned_data['comment']
            )
            return redirect(reverse('posts:detail', kwargs = {'id': post.id}))

        return render(request, "posts/detail.html", {"post": post, "review_form": reviews_form})

class EditReviewView(LoginRequiredMixin, View):
    def get(self, request, post_id, review_id):
        post = Post.objects.get(id=post_id)
        review = post.postreview_set.get(id=review_id)
        review_form = PostReviewForm(instance=review)

        return render(request, "posts/edit_review.html", {"post": post, "review": review, "review_form": review_form})

    def post(self, request, post_id, review_id):
        post = Post.objects.get(id=post_id)
        review = post.postreview_set.get(id=review_id)
        review_form = PostReviewForm(instance=review, data=request.POST)

        if review_form.is_valid():
            review_form.save()
            return redirect(reverse("posts:detail", kwargs={'id':post_id}))

        return render(request, "posts/edit_review.html", {"post": post, "review": review, "review_form": review_form})

class ConfirmDeleteReview(LoginRequiredMixin, View):
    def get(self, request, post_id, review_id):
        post = Post.objects.get(id=post_id)
        review = post.postreview_set.get(id=review_id)
        return render(request, "posts/confirm_delete_review.html", {"post":post, "review":review})

class DeleteReviewView(LoginRequiredMixin, View):
    def get(self, request, post_id, review_id):
        post = Post.objects.get(id=post_id)
        review = post.postreview_set.get(id=review_id)
        review.delete()
        # messages.success(request, "You have successfully deleted this review")

        return redirect(reverse("posts:detail", kwargs={'id': post_id}))

posts/templates/posts/confirm_delete_review.html
{% extends 'base.html' %}
{% block title %}Confirm Delete Review{% endblock %}

{% block content %}
    <h3>Bu izohni o'chirishga aminmisan?</h3>

    <p>
        <b>Post:</b> {{ post.title }}
    </p>

    <p>
        <b>Izoh:</b> {{ review.comment }}
    </p>
<a class="btn btn-outline-danger" href="{% url 'posts:delete-review' post.id review.id %}">Ha</a>  <a class="btn btn-outline-primary" href="{% url 'posts:detail' post.id  %}">Yo'q</a>
{% endblock %}

posts/templates/posts/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Create Post{% endblock %}

{% block content %}
    <h1>Yangi Post Yaratish</h1>
    <div class="row mb-4">
        <div class="col-6">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-success">Saqlash</button>
            </form>
        </div>
    </div>
    <a href="{% url 'posts:list' %}">⬅️ Orqaga</a>
{% endblock %}

posts/templates/posts/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Post Detail Page{% endblock %}

{% block content %}
    <div class="row mb-3">
        <div class="col-3">
            <img class="post_pic" src="{{ post.post_picture.url }}" alt="post picture">
        </div>

        <div class="col-6 ms-3">

            <h3>{{ post.title }}</h3>

            <span>
                Muallif:
                {% for post_author in post.postauthor_set.all %}
                    {{ post_author.author.full_name }}
                {% endfor %}
            </span>
            <p>
                {{ post.description }}
            </p>

        </div>
    </div>
    <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'posts:reviews' post.id %}">
                {% csrf_token %}
                {{ review_form | crispy }}
                <button class="btn btn-success">Add review</button>
            </form>
        </div>
    </div>
    {% if post.postreview_set.exists %}

        <h4>Reviews</h4><hr>

        {% for review in post.postreview_set.all %}
            <div class="row mb-3">
                <div class="col-1 me-3">
                    <img class="small_profile-pic" src="{{ review.user.profile_picture.url }}" alt="">
                </div>
                <div class="col-7">
                    <b>{{ review.user.username }}</b> rated it {{ review.stars_given }} stars <span class="fw-lighter">{{ review.created_at }}</span>
                    {% if review.user == request.user %}
                        <a href="{% url 'posts:edit-review' post.id review.id %}"><i class="bi bi-pencil"></i></a>
                        <a href="{% url 'posts:confirm-delete-review' post.id review.id %}"><i class="bi bi-trash3"></i></a>
                    {% endif %}
                    <p class="mt-2 font-monospace fs-6">{{ review.comment }}</p>
                </div>
            </div>
        {% endfor %}

    {% endif %}

{% endblock %}

posts/templates/posts/edit_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %} Edit review {% endblock %}

{% block content %}
    <h3>Edit review</h3>

     <div class="row mb-4">
        <div class="col-6">
            <form method="post" action="{% url 'posts:edit-review' post.id review.id %}">
                {% csrf_token %}
                {{ review_form | crispy }}
                <button class="btn btn-success">Save</button>
            </form>
        </div>
    </div>

{% endblock %}

posts/templates/posts/home.html
{% extends "base.html" %}

{% block title %}Postlar{% endblock %}

{% block content %}

<div class="container2">
    <!-- Yangi postlar -->
    <div class="column mb-5">
        <h2>Yangi postlar</h2>
        <br>
        {% for post in new_posts %}
            <div class="post">
                <a href="{% url 'posts:detail' post.id %}">
                    <img class="post_pic" src="{{ post.post_picture.url }}" alt="Post image">
                    <h3>{{ post.title }}</h3>
                    <p>{{ post.description|truncatewords:5 }}</p>
                </a>
                <p>
                    <small>
                        Yaratilgan sana:
                        {% if post.created_at %}
                            {{ post.created_at | date:"Y-m-d  H:i" }}
                        {% endif %}
                    </small>
                </p>

            </div><hr><br>
        {% endfor %}
    </div>

    <!-- Yaqinda ko‘rilganlar -->
    <div class="column mb-5">
        <h2>Yaqinda ko‘rilganlar</h2>
        {% for post in recent_viewed_posts %}
            <div class="post">
                <a href="{% url 'posts:detail' post.id %}">
                     <img class="post_pic" src="{{ post.post_picture.url }}" alt="Post image">
                    <h3>{{ post.title }}</h3>
                    <p>{{ post.description|truncatewords:5 }}</p>

                </a>
                <p>
                    <small>Ko'rilgan sana: {{ post.last_viewed_at | date:"Y-m-d  H:i" }}</small>
                </p>
            </div><hr><br>
        {% endfor %}
    </div>

    <!-- Eng ko‘p ko‘rilganlar -->
    <div class="column mb-5">
        <h2>Eng ko‘p ko‘rilganlar</h2>
        {% for post in most_viewed_posts %}
            {% if post.views_count > 0 %}
                <div class="post">
                    <a href="{% url 'posts:detail' post.id %}">
                        <img class="post_pic" src="{{ post.post_picture.url }}" alt="Post image">
                        <h3>{{ post.title }}</h3>
                        <p>{{ post.description|truncatewords:5 }}</p>
                    </a>
                        <p>
                            <small>
                                Ko'rishlar soni: {{ post.views_count }}
                            </small>
                        </p>

                </div><hr><br>
            {% endif %}
        {% empty %}
            <p>Hozircha hech qanday post ko'rilmagan.</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

posts/templates/posts/list.html
{% extends "base.html" %}
{% block title %}Posts Page{% endblock %}

{% block content %}

    <h1>Tasdiqlangan Postlar</h1>
    <div>
        {% if posts %}
            <ul>
              {% for post in posts %}
                <li>
                    <a href="{% url 'posts:detail' post.id %}">
                        <img  class="post_icon" src="{{ post.post_picture.url }}" alt="post picture">
                    </a>
                </li>
                <li>
                  <a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a>
                </li>
                <span>
                    <strong>Muallif:</strong>
                    {% with post.postauthor_set.first.author as author %}
                        {{ author.full_name }}
                    {% endwith %}
                </span>
                <br>
              {% endfor %}
            </ul>
        {% else %}
         No posts found
    </div>

    {% endif %}

{% endblock %}